### ISSUE TITLE
tag name and tag description does not fit

### ISSUE THREAD

**Issue by niklaswr** [HPSCTerrSys/TSMP#110]
## Describe the problem
The tag name `v1.2.3` does not fit its description which is `v1.2.2`. This is at least valid for tag `v1.2.3`, but I did not test other tags.
Even if this is not a big issue, this leads to quiet some confusion.

## Version and Component Models 
TSMP-Version: 
commit 10a4cb33194dd65dec0b6310318e35b8adbe7d25
tag `v1.2.3`

## Reproduction of the error
``` bash
>> git clone https://github.com/HPSCTerrSys/TSMP.git
>> cd TSMP
>> git checkout v1.2.3
>> git log
commit 10a4cb33194dd65dec0b6310318e35b8adbe7d25 (HEAD, tag: v1.2.3)
Author: Abouzar Ghasemi <a.ghasemi@fz-juelich.de>
Date:   Tue Dec 1 15:27:00 2020 +0100

    Porting TSMP on JUSUF and JURECA_DC
[...]
>> git describe --abbrev=0
v1.2.2
>> git describe 
v1.2.2-2-g10a4cb3
>> git describe --tags
v1.2.3
```

## Expected behavior
I would expect that the tag name and its description does fit each other.

## Additional context
Next to the inconsistency of tag name and description, which is not nice to read :smiley:  , the observed behavior leads to misunderstandings e.g. in case one tries to track the exact setup used for some specific simulations by git stats, as I do.

**Comment by jjokella** [comment]
The problem seems to be that `v1.2.3` is a lightweight tag instead of an annotated tag

https://stackoverflow.com/questions/40479712/how-can-i-tell-if-a-given-git-tag-is-annotated-or-lightweight

Try seeing this by:
```sh
git for-each-ref refs/tags
```
Now I have changed `v1.2.3` using

https://stackoverflow.com/questions/5002555/can-a-lightweight-tag-be-converted-to-an-annotated-tag

`v1.2.3` should be an annotated tag now.

For the future, we should always create annotated version tags!  (`git tag -a ...`)

@niklaswr For my local setup, `git describe` works as expected now. Can you test after updating your repo and if it works close the issue?

**Comment by niklaswr** [comment]
Tags are working as expected now.
Thanks Johannes!
