### ISSUE TITLE
TSMP-PDAF: Setting PDAF-Statevector in PF2ENKF for Subgrids

### ISSUE THREAD

**Issue by jjokella** [HPSCTerrSys/TSMP#113]
In `PF2ENKF` from `enkf_parfow.c:491`, the Subgrids are iterated and data from a ParFlow `Vector` is written to `enkf_subvec`.

`enkf_subvec` is iterated using `counter` which is started at `int counter = 0` for each Subgrid.

Does this mean that `enkf_subvec` is overwritten, when a new Subgrid is entered?

**Comment by kvrigor** [comment]
Yes, since `enkf_subvec` is declared as a pointer. Also, it appears that the purpose of `PF2ENKF()` is to return a PDAF grid representation (thru `enkf_subvec`) from a given ParFlow grid.

https://github.com/HPSCTerrSys/TSMP/blob/1b66c05d90a1b9214ab2f778962d89de6ecf4b38/bldsva/intf_DA/pdaf1_1/model/enkf_parflow.c#L467-L501
